### ISSUE TITLE
bug: second take() hangs after disconnect during take()

### ISSUE THREAD

**Issue by Totktonada** [tarantool/queue#104]
@Mons describes the following case when take() may hang.

Take a task from a connector (say, net.box), disconnect and connect again, try to take this task again. It is stated that the second take will (may?) hang.

It seems that something like this was fixed in xqueue here: https://github.com/moonlibs/xqueue/commit/eb501508c9ffc7ca5f56613a41458d2bb3c0843a

Let's verify it, fix and cover with a test.

**Comment by LeonidVas** [comment]
Looks like it has been  fixed twice in https://github.com/tarantool/queue/issues/103 and https://github.com/tarantool/tarantool/issues/4627

**Comment by LeonidVas** [comment]
D'oh, I was wrong. This unrelated to #103 bug.
