### ISSUE TITLE
Fifottl, utubettl and priorities

### ISSUE THREAD

**Issue by rybakit** [tarantool/queue#14]
```lua
> fifottl:put('pri1', {pri=1})
> fifottl:put('pri2', {pri=2})
> task1 = fifottl:take(.1)
> task2 = fifottl:take(.1)
> task1
---
- [0, 't', 'pri1']
...
> task2
---
- [1, 't', 'pri2']
...
```
```lua
> utubettl:put('pri1', {pri=1})
> utubettl:put('pri2', {pri=2})
> task1 = utubettl:take(.1)
> task2 = utubettl:take(.1)
> task1
---
- [0, 't', 'pri1']
...
> task2
---
- null
...
```
Is it a bug or intended behaviour for `utubettl` queue?

**Comment by bigbes** [comment]
Yes, it's intended behaviour - utube is microtube - one task only per user. 
> Особенности. Работает аналогично fifo. В этой очереди так же нет ttl, ttr итп. Отличие в том, что каждый put принимает в опциях параметр utube - имя микроочереди. Два таска одновременно не могут быть взяты из одной микроочереди.
