### ISSUE TITLE
tube.grant don't provide access to queue.statistics and queue.tube.tube_name:put procedures

### ISSUE THREAD

**Issue by maxpetriev** [tarantool/queue#151]
It seems [tube.grant](https://github.com/tarantool/queue/blob/master/queue/abstract.lua#L250) was designed to provide user access to all tube methods but it doesn't grant access to [queue.statistics](https://github.com/tarantool/queue#getting-statistics) and [queue.tube.tube_name:put](https://github.com/tarantool/queue#putting-a-task-in-a-queue).  
Do I understand the purpose of tube.grant correctly?

**Comment by rybakit** [comment]
Duplicate of https://github.com/tarantool/queue/issues/115.

**Comment by LeonidVas** [comment]
Closed as a duplicate.
