### ISSUE TITLE
Broken link at tarantool.org

### ISSUE THREAD

**Issue by dedok** [tarantool/queue#17]
URL: http://tarantool.org/doc/getting_started.html#starting-tarantool-and-making-your-first-database
'configure' link me to http://tarantool.org/doc/:mod:`box.cfg`.

**Comment by rybakit** [comment]
The issue should be created in [tarantool/tarantool](https://github.com/tarantool/tarantool) repository, where the docs are located.

**Comment by Sulverus** [comment]
Moved to https://github.com/tarantool/tarantool/
