### ISSUE TITLE
Flaky/broken test vinyl-040-utubettl.t

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/queue#194]
Commit https://github.com/tarantool/tarantool/commit/588170a77c9aba3d0cf898d0134286c6ffd46339 has changed behavior of vinyl. This might have broken the test's expectations. The test almost always fails in the integration job: https://github.com/tarantool/tarantool/actions/runs/3264906596/jobs/5369677748

```
12:   ---
12:   filename: /home/runner/work/tarantool/tarantool/t/040-utubettl.t
12:   trace:
12:   - line: 245
12:     source: '@builtin/tap.lua'
12:     filename: builtin/tap.lua
12:     what: Lua
12:     namewhat: method
12:     name: test
12:     src: builtin/tap.lua
12:   - line: 0
12:     source: '@/home/runner/work/tarantool/tarantool/t/040-utubettl.t'
12:     filename: /home/runner/work/tarantool/tarantool/t/040-utubettl.t
12:     what: main
12:     namewhat: 
12:     src: /home/runner/work/tarantool/tarantool/t/040-utubettl.t
12:   planned: 3
12:   failed: 1
12:   line: 0
12:   ...
...


Total Test time (real) =  71.78 sec

The following tests FAILED:
	 12 - vinyl-040-utubettl.t (Failed)
```

**Comment by locker** [comment]
What was changed by commit https://github.com/tarantool/tarantool/commit/588170a77c9aba3d0cf898d0134286c6ffd46339: a read (get, select) outside a transaction now never returns unconfirmed data (committed, but not yet written to WAL).

**Comment by oleg-jukovec** [comment]
> What was changed by commit [tarantool/tarantool@588170a](https://github.com/tarantool/tarantool/commit/588170a77c9aba3d0cf898d0134286c6ffd46339): a read (get, select) outside a transaction now never returns unconfirmed data (committed, but not yet written to WAL).

So it is expected that the update yield now:

https://github.com/tarantool/queue/blob/master/queue/abstract/driver/utubettl.lua#L138-L141

?

**Comment by locker** [comment]
> > a read (get, select) outside a transaction now never returns unconfirmed data (committed, but not yet written to WAL).
> 
> So is it expected that the update yield now:
> 
> https://github.com/tarantool/queue/blob/master/queue/abstract/driver/utubettl.lua#L138-L141
> 
> ?

Update in Vinyl may yield anyway. It could yield before the aforementioned commit.

**Comment by locker** [comment]
Switching single-statement reads to the 'read-committed' isolation level (may be done only at compile time) eliminates the issue.

<details><summary>Patch for Tarantool</summary>

```diff
diff --git a/src/box/vy_tx.c b/src/box/vy_tx.c
index 7f2af76888d4..79e143c61d33 100644
--- a/src/box/vy_tx.c
+++ b/src/box/vy_tx.c
@@ -341,7 +341,7 @@ vy_tx_create(struct vy_tx_manager *xm, struct vy_tx *tx)
 	tx->write_set_version = 0;
 	tx->write_size = 0;
 	tx->xm = xm;
-	tx->isolation = TXN_ISOLATION_READ_CONFIRMED;
+	tx->isolation = TXN_ISOLATION_READ_COMMITTED;
 	tx->state = VINYL_TX_READY;
 	tx->is_applier_session = false;
 	tx->read_view = (struct vy_read_view *)xm->p_global_read_view;
```

</details>
