### ISSUE TITLE
Statistics doesn't cleared after dropping a tube

### ISSUE THREAD

**Issue by rybakit** [tarantool/queue#22]
```lua
> t = queue.create_tube('t', 'fifottl')
---
…

> queue.statistics('t')
---
- []
…

> t:put(1)
---
- [0, 'r', 1]
…

> queue.statistics('t')
---
- - t:
      tasks:
      - total: 1
      - ready: 1
      - taken: 0
      - buried: 0
      - done: 0
      - delayed: 0
      calls:
      - put: 1

> t:drop()
---
- true
…

> queue.statistics() <— should not raise an error
---
- error: '/home/vagrant/.luarocks/share/lua/5.1/queue/abstract.lua:380: attempt to
    index a nil value'
...


> queue.statistics('t')
---
- error: '/home/vagrant/.luarocks/share/lua/5.1/queue/abstract.lua:380: attempt to
    index a nil value'
…

> queue.statistics('non_exsisting_tube')
---
- []
…

> t = queue.create_tube('t', 'fifottl')
---
…

> queue.statistics('t')
---
- - t:
      tasks:
      - total: 0
      - ready: 0
      - taken: 0
      - buried: 0
      - done: 0
      - delayed: 0
      calls:
      - put: 1  <— should be 0
...
```

**Comment by rybakit** [comment]
Also, `statistics()` returns a number of done tasks, but, as far as I can see, it's always 0. If so, should it be removed from the stat table?

**Comment by Sulverus** [comment]
1. statistics bug after queue drop fixed
2. net box call queue.statistics() fixed with wrapping

Found strange behavior of `tube:ack()`: new task state is not saved after ack execution, that's why done counter is always 0.

**Comment by rybakit** [comment]
I also found that `calls.bury` counter is missing for `utubettl` queue.

**Comment by rybakit** [comment]
@Sulverus `delete` doesn’t update the `done` counter either. 

Here is my test case:
```lua
t:put('stat_0')
t:put('stat_1')
t:put('stat_2')
t:put('stat_3')
t:put('stat_4')
t:delete(4)
t:take(.001)
t:release(0)
t:take(.001)
t:ack(0)
t:bury(1)
t:bury(2)
t:kick(1)
t:take(.001)
```
What I expect:
```lua
tasks:
  taken: 1
  buried: 1
  ready: 1
  done: 2
  delayed: 0
  total: 3
calls:
  delete: 1
  ack: 1
  take: 3
  kick: 1
  release: 1
  put: 5
  bury: 2
```
What I get:
```lua
tasks:
  taken: 1
  buried: 1
  ready: 1
  done: 0
  delayed: 0
  total: 3 
calls:
  delete: 2 -- missing for utubettl
  take: 3
  kick: 1
  release: 1
  put: 5
  bury: 2  -- missing for utubettl
```

**Comment by Sulverus** [comment]
Totaly:
1. updated `done` counter for all drivers
2. fixed `delete`, `ack` and `bury` in utubettl
3. added test cases for all drivers(based on your example)

Please review https://github.com/tarantool/queue/commit/2efb6ac5ce25aade955d4555e7cebe2502c9abb9

@rybakit  thank you for research

**Comment by rybakit** [comment]
I would also add test cases for `delayed` counter for `*ttl` queues (I didn't do it in my example, as I have [a separate test case for that](https://github.com/tarantool-php/queue/blob/stat/tests/Integration/Ttl.php#L65)).

**Comment by Sulverus** [comment]
statistics test case updated with `delayed` tasks for `fifottl` and `utubettl`: https://github.com/tarantool/queue/commit/4e4ac7cd894e1169dd32b33d48f4f62ee1443ebc
merged.
