### ISSUE TITLE
it's quite nice implementation in lua + redis

### ISSUE THREAD

**Issue by plandem** [tarantool/queue#35]
https://github.com/seomoz/qless

Maybe take some features from there? E.g., tagging, heartbeat

**Comment by bigbes** [comment]
Hello, @plandem . Thank you for your issue. Don't you mind to show us what features do you want in queue?

**Comment by plandem** [comment]
ok QLess features list with priority:
1) Tagging / Tracking
2) Job Dependencies
3) Scheduled Work
4) Recurring Jobs

**Comment by plandem** [comment]
But i suppose your implementation is closer to **beanstalkd** instead of **rescue**.

**Comment by bigbes** [comment]
You're absolutely right, it was based on **beanstalk** API.
Also, it seems to me that some of this features can be implemented in Tarantool using Lua:
3 - **Scheduled work** - use delay argument for a task.
4 - **Recurring job** can be implemented with simple background fiber, that adds job to queue and sleep for N seconds
1 and 2 can't be implement in this queue, without major rewriting/refactoring. Feel free to open PR/Issues for every of this "features" OR you can write alternative one.
