### ISSUE TITLE
Concurrent consumers got same task from queue

### ISSUE THREAD

**Issue by dmitry-sobolev** [tarantool/queue#46]
Hello,

I've tried to create system with one producer and 5 consumers using tarantool queue and later i've noticed that sometimes two workers getting same task. Is there a way to avoid this issue or I just should use another queue for my purposes?

**Comment by kostja** [comment]
Please provide more details about the problem. Are you using a single master or multi-master set up? Do you use task timeouts? A reproducible test case would be perfect.
If you did everything right, you'd never have two workers getting the same task.

**Comment by dmitry-sobolev** [comment]
I'm using single master and not using timeouts. I am working on test case.

**Comment by bigbes** [comment]
This tasks have same id?

With best regards, Eugene.

2016-12-03 23:26 GMT+03:00 Dmitry Sobolev <notifications@github.com>:

**Comment by dmitry-sobolev** [comment]
> This tasks have same id?
Yes.

**Comment by bigbes** [comment]
Maybe you hadn't ack'ed tasks or used release or have client disconnections?

**Comment by dmitry-sobolev** [comment]
> Maybe you hadn't ack'ed tasks or used release or have client disconnections?

I've ack'ed them, but yes maybe I have disconnection. I'll try to investigate this case.

**Comment by dmitry-sobolev** [comment]
It seems like these errors were result of errors in my code
