### ISSUE TITLE
FR: add method "prolong ttr"

### ISSUE THREAD

**Issue by aensidhe** [tarantool/queue#47]
Hello.

We are using queue for passing tasks to background service. Unfortunately, at the moment of task creation exact volume of work is unknown and can vary from task to task on orders of magnitude. I would like to set low TTR on all tasks initially in such way that a majority of tasks will succeed before TTR will expire

But other, larger tasks need to prolong TTR by somehow. And it would be great if this will be done by queue interface, not by some hacks via underlying spaces.

Would you accept this feature and should I start to work on pull request?

**Comment by bigbes** [comment]
> Would you accept this feature and should I start to work on pull request?
Yes, we would.

You may use [this](https://github.com/tarantool/queue/blob/stable/init.lua#L889-L921) code as an inspiration.
