### ISSUE TITLE
Delete ttl tasks using delete method

### ISSUE THREAD

**Issue by andyudina** [tarantool/queue#51]
Now ttl tasks are deleted directly from queue: https://github.com/tarantool/queue/blob/master/queue/abstract/driver/fifottl.lua#L138
Should use delete method https://github.com/tarantool/queue/blob/master/queue/abstract/driver/fifottl.lua#L269 instead

**Comment by fsitedev** [comment]
Similar problem also on ttr tasks:
https://github.com/tarantool/queue/blob/master/queue/abstract/driver/fifottl.lua#L157
