### ISSUE TITLE
Возможность задавать свой идентификатор задачи

### ISSUE THREAD

**Issue by tucibi** [tarantool/queue#53]
Необходимо в произвольный момент времени вытаскивать произвольную задачу, ID которой мне известен. Можно дополнительно сохранять айдишники задач, но это оверхед, который подкидывает проблемы синхронизации, а возможность задавать свой идентификатор задачи решает проблему просто.

**Comment by bigbes** [comment]
Используйте `on_task_change` коллбек для манипуляции с ID задачами.

**Comment by tucibi** [comment]
@bigbes, спасибо за совет. Но, по-моему, намного удобнее задавать свои айдишники и уже по ним вытаскивать задачи, при необходимости.
Могу я узнать причину отказа?

**Comment by bigbes** [comment]
Возможность конфигурировать айдишники для тасок несет под собой пласт проблем, которые потенциально трудно откопать.

**Comment by kostja** [comment]
Господа, вы не хотите продолжить в Telegram? Github - прикольная штука для feature requests, но не подходит для обсуждений да ещё и на русском.

**Comment by bigbes** [comment]
И для приложения, и как следствие, для клиента. заходите на [канал](https://telegram.me/tarantoolru)
