### ISSUE TITLE
Broken queue after update tarantool

### ISSUE THREAD

**Issue by zloidemon** [tarantool/queue#64]
```
Tarantool 1.7.5-195-gcaacfef
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

Output
```
tarantool> queue = require 'queue'
---
- error: Ambiguous field type, field 1. Requested type is string but the field has
    previously been defined as unsigned
...
```

**Comment by Totktonada** [comment]
Can you clarify from which tarantool version you update to which one?

If you remember it…

**Comment by Totktonada** [comment]
It seems, a definition of some space was changed in the past without an upgrade scenario in a mind. Anyway, it was a long time ago and it seems the issue unlikely will affect anyone now. I'll close it. Feel free to reopen if it is still relevant for you and you can provide more information: say, from old and new queue versions, between which the update is broken.
