### ISSUE TITLE
why call on_task_change with nil?

### ISSUE THREAD

**Issue by aleclarson** [tarantool/queue#74]
https://github.com/tarantool/queue/blob/593c9f6f949c84865bcd383d542876ebbc93520a/queue/abstract/driver/utube.lua#L102-L104

We shouldn't call `on_task_change(nil, 'delete')` since a nil task indicates the task has already been removed from the queue, which means `on_task_change` was already called before when the task was previously deleted or acknowledged.

I assume this is being done in other queue types, too.

I'll send a pull request if you agree.

**Comment by Totktonada** [comment]
It would not change behaviour of queue itself, but would improve correctness when calling user-provided `on_task_change` callback. So I would consider it as the bugfix.
