### ISSUE TITLE
Добавить возможность получить количество элементов в очереди

### ISSUE THREAD

**Issue by marrrvin** [tarantool/queue#9]
Желательно, с возможностью фильтровать по статусу задачи.

**Comment by kostja** [comment]
Please document this (if this is 1.6, otherwise implement & document).

**Comment by Sulverus** [comment]
for 1.5: https://github.com/tarantool/queue/tree/stable#queuestatistics
for 1.6: implemented in https://github.com/tarantool/queue/tree/gh-9-stats

Awaiting for code review

**Comment by rybakit** [comment]
To create a queue (tube) a user just specify a tube name, but to get statistics they have to provide a full space name, which I find inconsistent. Also, it exposes implementation details to users.

**Comment by Sulverus** [comment]
Agree. But what we gonna do in this situation:
```lua
queue.create_tube('test', 'fifottl')
queue.create_tube('test2', 'fifo')
```
now we take 2 queues. if get statistics with tube name - return 2 queues data?

**Comment by rybakit** [comment]
We can update the signature of the `statistics()` method to something like `queue.statistics([tube_type [, tube_name]])`. Or pass a full space name to `create_tube()` instead of a tube name. I prefer the latter, as it's more explicit and flexible. I recall that I had some problems with creating a tube with a long name.

**Comment by Sulverus** [comment]
I think it's right way to strict this case in create_tube().

**Comment by Sulverus** [comment]
Max space name length - 32 characters. it specified in tarantool database

**Comment by Sulverus** [comment]
Done
https://github.com/tarantool/queue/commit/bf7c9691a3a3e1ef8a24b7b785e5347c41f49f2d

**Comment by Sulverus** [comment]
merged
